### PR TITLE
Fix FieldInfo Parameters Mismatch

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Fix the breaking change coming from https://github.com/apache/lucene/pull/12829 which is failing the build due to mismatch in FieldInfo parameters.
 
```
/__w/k-NN/k-NN/src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java:168: error: constructor FieldInfo in class FieldInfo cannot be applied to given types;
            return new FieldInfo(
                   ^
  required: String,int,boolean,boolean,boolean,IndexOptions,DocValuesType,long,Map<String,String>,int,int,int,int,VectorEncoding,VectorSimilarityFunction,boolean,boolean
  found: String,int,boolean,boolean,boolean,IndexOptions,DocValuesType,long,Map<String,String>,int,int,int,int,VectorEncoding,VectorSimilarityFunction,boolean
  reason: actual and formal argument lists differ in length
```
 
### Check List
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by naveentatikonda** [comment]
We already have an issue created for Failing Rolling Upgrade Tests
https://github.com/opensearch-project/k-NN/issues/1481

**Comment by martin-gaievski** [comment]
what is the lucene version with that change that has been adopted by core?

**Comment by naveentatikonda** [comment]
> what is the lucene version with that change that has been adopted by core?

From 9.9.2 to 9.10.0 https://github.com/opensearch-project/OpenSearch/pull/12392/files

**Review by ryanbogan — APPROVED** [review]
LGTM!

**Comment by naveentatikonda** [comment]
> do we need to do routine for knn codec version bump?

We can do it when the build fails
