### ISSUE TITLE
[BUG] Upstream Client dependency package moved

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/k-NN#2512]
**What is the bug?**

KNN needs to change imports for 3.0.0 breaking changes in https://github.com/opensearch-project/OpenSearch/pull/17272

**How can one reproduce the bug?**

See failing builds https://github.com/opensearch-project/k-NN/actions?query=branch%3Amain

```
/Users/runner/work/k-NN/k-NN/src/main/java/org/opensearch/knn/plugin/rest/RestClearCacheHandler.java:11: error: package org.opensearch.client.node does not exist
import org.opensearch.client.node.NodeClient;
                                 ^
```

**What is the expected behavior?**

Main branch compiles

**What is your host/environment?**

Downstream plugin depending on KNN

**Do you have any additional context?**

`s/o.o.client.Client/o.o.transport.client.Client/g`
`s/o.o.client.node.NodeClient/o.o.transport.client.node.NodeClient/g`

**Comment by jmazanec15** [comment]
Fixed in #2442 - closing

**Comment by peterzhuamazon** [comment]
One more fix: https://github.com/opensearch-project/k-NN/pull/2526
